allowBuilds:
  unrs-resolver: false

autoInstallPeers: false

minimumReleaseAge: 720

minimumReleaseAgeExclude:
  - "@codemod-utils/*"
  - "@ijlee2-frontend-configs/*"

overrides:
  ember-cli-htmlbars: ^7.0.1

packages:
  - "blueprints/v2-addon"
  - "configs/**"
  - "docs-app"
  - "packages/**"
  - "test-app"

publicHoistPattern:
  - "*eslint*"
  - "*prettier*"
  - "*stylelint*"

resolvePeersFromWorkspaceRoot: false

verifyDepsBeforeRun: "warn"
